/** @type {import('next').NextConfig} */
const nextConfig = {
  serverExternalPackages: ["sharp"],
  // Allow the laptop's wifi IP so iPhone HMR + dev requests aren't blocked
  // as cross-origin when hitting the dev server over the local network.
  // Add whatever local-network IPs the laptop hops between (hotspot, home wifi, etc.).
  // These are LAN-only addresses, safe to allow in dev.
  allowedDevOrigins: ["172.20.10.14", "192.168.1.116", "192.168.1.0/24"],

  // SPA fallback for the Expo web app hosted at /app (files live in
  // public/app/, generated by `npm run build:webapp`). `afterFiles`
  // rewrites run AFTER the filesystem + public/ lookup, so real assets
  // (the JS bundle under /app/_expo/..., images under /app/assets/...,
  // /app/index.html itself) are served directly and only client-side
  // routes with no physical file (e.g. /app/sign-in on a hard reload)
  // fall through to index.html, where expo-router takes over.
  async rewrites() {
    return {
      afterFiles: [
        { source: "/app", destination: "/app/index.html" },
        { source: "/app/:path*", destination: "/app/index.html" },
      ],
    };
  },
};

module.exports = nextConfig;
